"""
mc_kickoff.py

Simple utility to run a sequence of MC simulations leveraging all the
equity models in this repository and using a portfolio comprising
of Long equity with T-Bill/T-Note ladders.
"""

import argparse
import copy
import json
import math
import os
import sys
import time

import numpy as np

import market_modelling.path_simulation as ps

from monte_carlo import MonteCarloEngine
from portfolio_models.linear_models import LongSPYWithTreasuryLadders
from market_data.yf_fred_market_data import MarketDataManager

allocations = [
    (0.85, 0.15),
    (0.9, 0.1),
    (0.95, 0.05),
]

spendings = [
    150_000,
    155_000,
    160_000,
    165_000,
    170_000
]

class MCConfig():
    """"
    Represents a Monte Carlo simulation configuration, useful to generate
    multiple portfolio configs to feed it to the MC engine.
    """
    PORTFOLIO_CONFIG_TEMPLATE = {
        "type": "LongSPYWithTreasuryLadders",
        "equity_allocation": None,
        "ladder_allocation": None,
        "yearly_spending":  None,
        "dividend_yield": 0.01,
    }

    def __init__(self, *,
                 yearly_spending_floor: float = 150_000,
                 yearly_spending_ceil: float = 300_000,
                 starting_equity: float = 0.75,
                 ending_equity: float = 1.00,
                 weight_increments: float = 0.05,
                 spend_increments: float = 5000.0):
        self.yearly_low = yearly_spending_floor
        self.yearly_top = yearly_spending_ceil
        self.equity_low = starting_equity
        self.equity_top = ending_equity
        self.eq_increment = weight_increments
        self.spend_increment = spend_increments


    def portfolio_configs(self):
        """"
        Generates portfolio configuration by sweeping a range
        of yearly spendings and equity allocations.
        """
        yearly_low = int(self.yearly_low / 5000.0) * 5000
        yearly = yearly_low
        yearly_limit = int(self.yearly_top / 5000.0) * 5000
        equity = math.ceil(self.equity_low * 500) / 500.0
        equity_top = math.ceil(self.equity_top * 500) / 500.0
        fixed = 1.0 - equity
        while equity_top - equity > 0.0:
            while yearly <= yearly_limit:
                p = copy.deepcopy(self.PORTFOLIO_CONFIG_TEMPLATE)
                p["equity_allocation"] = equity
                p["ladder_allocation"] = fixed
                p["yearly_spending"] = yearly
                yield p
                yearly += self.spend_increment
            equity += self.eq_increment
            fixed = 1.0 - equity
            yearly = yearly_low


    def total_portfolios(self):
        """Returns the total count of portfolios generated by the given config."""
        yearly_totals = math.ceil((self.yearly_top - self.yearly_low) / self.spend_increment) + 1
        weight_totals = math.ceil((self.equity_top - self.equity_low) / self.eq_increment)
        return yearly_totals * weight_totals


def parse_args():
    "CLI argument parser"
    prog_description = """CLI tool that invokes MC simulation across all portfolio
    models using the Long Equity and Fixed Income Ladders strategy.

    Returns a CSV file with all the simulation results.
    """
    parser = argparse.ArgumentParser(description=prog_description)
    parser.add_argument("-c", "--config-file",
                        help="Config file in JSON format that contains the simulation parameters",
                        dest="config_filename",
                        required=True)
    parser.add_argument("-o", "--output-file",
                        help="Destination JSON file to store the results of the simulation",
                        dest="output_filename",
                        required=True)
    parser.add_argument("-m", "--market-cache-file",
                        help="Specifies an alternative parquet market data cache file",
                        default="market_data.parquet",
                        dest="market_data_filename")
    return parser.parse_args()


def main():
    "Main entrypoint"
    args = parse_args()
    mc_config = None
    initial_nav = None
    years_to_simulate = None
    total_paths = None
    workers = os.cpu_count()
    config = None
    try:
        with open(args.config_filename, encoding="utf-8") as f:
            config = json.load(f)
        mc_config = MCConfig(
            yearly_spending_floor=config["yearly_spending_floor"],
            yearly_spending_ceil=config["yearly_spending_ceil"],
            starting_equity=config["equity_floor"],
            ending_equity=config["equity_ceil"],
            weight_increments=config["weight_increments"],
            spend_increments=config["spend_increments"])
        initial_nav = config["initial_nav"]
        years_to_simulate = config["years_to_simulate"]
        total_paths = config["total_paths"]
        if "workers" in config:
            workers = config["workers"]
        mdm = MarketDataManager(cache_filepath=args.market_data_filename)
        levels, returns = mdm.get_aligned_real_returns()
    except Exception as exc:
        print(f"Error loading tool configuration: {str(exc)}", sys.stderr)
        sys.exit(1)

    assert mc_config is not None
    assert initial_nav is not None
    assert total_paths is not None
    assert years_to_simulate is not None

    print("Loaded configuration: ")
    kvs: dict[str, float] = [f"{k.replace('_', ' ').title()}: {v}" for k, v in config.items()]
    print(" ".join(kvs))


    models = [
        ps.RegimeSwitchingValuationVARSimulator,
        ps.RegimeSwitchingBootstrapSimulator,
        ps.RawBlockBootstrapSimulator,
        ps.HybridValuationVARSimulator,
        ps.VARResidualBootstrapSimulator,
        ps.ValuationAdjustedVARSimulator]

    results = {
        "initial_nav": initial_nav,
        "years": years_to_simulate,
        "total_paths": total_paths,
        "simulations": {},
        "perf_data": {}
    }

    i = 0
    rng = np.random.default_rng()
    total = len(models) * mc_config.total_portfolios()
    perf_counters = {}

    for m in models:
        results["simulations"][m.name()] = []
        perf_counters[m.name()] = {}
        perf_counters[m.name()]["setup"] = []
        perf_counters[m.name()]["simulation"] = []
        perf_counters[m.name()]["data_storage"] = []

        portfolios = mc_config.portfolio_configs()
        for p in portfolios:
            print(f"Running simulation #{i + 1} out of {total}. Progress: {i * 100.0 / total:.2f}%")
            print(f"Model: {m.name()}, Yearly Spending: {p["yearly_spending"]}, "
                  f"Equity: {p["equity_allocation"] * 100.0:.2f}")
            setup_start = time.perf_counter()

            simulator = m()
            simulator.fit(returns, levels)

            strategy = LongSPYWithTreasuryLadders.from_json_object(p)
            mc = MonteCarloEngine(strategy, simulator, years_to_simulate * 12,
                                  initial_nav, rng.integers(1 << 32))

            setup_end = time.perf_counter()

            perf_counters[m.name()]["setup"].append(setup_end - setup_start)

            sim_start = time.perf_counter()
            spx, nav, ruin_histogram = mc.run(total_paths=total_paths, n_workers=workers)
            sim_end = time.perf_counter()

            perf_counters[m.name()]["simulation"].append(sim_end - sim_start)

            data_start = time.perf_counter()
            run_output = {
                    "Terminal SPX": spx.tolist(),
                    "Terminal NAV": nav.tolist()
            }
            results["simulations"][m.name()].append({
                "spending": p["yearly_spending"],
                "equity": p["equity_allocation"],
                "ladder": p["ladder_allocation"],
                "ruin_histogram": ruin_histogram.tolist(),
                "results": run_output
            })
            data_end = time.perf_counter()
            perf_counters[m.name()]["data_storage"].append(data_end - data_start)
            i += 1

    results["perf_data"] = perf_counters

    with open(args.output_filename, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=4)

if __name__ == '__main__':
    main()
